### ISSUE TITLE
Submitting an URL with the enter key is broken under Firefox

### ISSUE THREAD

**Issue by strangeglyph** [00SteinsGate00/MusicServer#3] opened 2017-01-13 22:28 UTC
Firefox only enables submitting with enter if there is an input with type="submit" within the same form

**Comment by j-holub** [comment] 2017-01-16 20:09
The Issue is resolved in the latest version. I changed the input overall to a form. Thanks for the Feedback and the suggestion, this should improve overall cross browser stability.

**Closed as completed** 2017-01-16 20:08 UTC
